Create a test for Response class
wearesho-team/ubki pull request #5
Opened 2018-04-18 14:39 UTC by siplowski

2018-04-18 15:32 UTC, Horat1us approved these changes

2018-04-18 15:40 UTC, sashabeton requested changes

2018-04-18 15:40 UTC, sashabeton commented on tests/Authorization/ResponseTest.php
> +
Не хватает phpdoc с типом

2018-04-18 15:40 UTC, sashabeton commented on tests/Authorization/ResponseTest.php
> +
Нет смысла объявлять setUp(), если в классе один тест

2018-04-18 15:41 UTC, sashabeton commented on tests/Authorization/ResponseTest.php
> +
Соответственно, не нужно будет объявлять лишнее свойство

2018-04-19 12:02 UTC, Horat1us requested changes

2018-04-19 12:02 UTC, Horat1us commented on tests/Authorization/ResponseTest.php
> +     * @return void
Зачем тут phpDoc?

https://github.com/wearesho-team/php-code-conventions#-В-phpdoc-в-возвращаемом-значении-не-надо-указывать-void-и-null

Его нужно указать в типе функции 
```php
<?php
function setUp(): void 
{}
```

2018-04-19 12:02 UTC, Horat1us commented on tests/Authorization/ResponseTest.php
> +     * @return void
Этот phpDoc тоже не нужен

2018-04-19 15:11 UTC, sashabeton requested changes

2018-04-19 15:11 UTC, sashabeton commented on tests/Authorization/ResponseTest.php
> +    public function setUp():void
setUp(): void
Необходимо ставить пробел между двоеточием и типом

2018-04-19 15:11 UTC, sashabeton commented on tests/Authorization/ResponseTest.php
> +    public function testGets():void
Аналогично

2018-04-19 15:19 UTC, sashabeton approved these changes

2018-04-20 07:49 UTC, Horat1us requested changes
Необходимо сделать rebase коммитов

2018-04-20 07:49 UTC, Horat1us commented on tests/Authorization/ResponseTest.php
> +        /** @var Ubki\Authorization\Response */
Зачем этот комментарий?

2018-04-20 08:56 UTC, Horat1us approved these changes

2018-05-07 17:13 UTC, Horat1us approved these changes

2018-05-07 17:14 UTC, merged